//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.02 at 06:49:04 PM CEST 
//


package entities.amendment;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import entities.act.Alineja;
import entities.act.Clan;
import entities.act.NormativniDeo;
import entities.act.Stav;
import entities.act.Tacka;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;sequence maxOccurs="unbounded">
 *           &lt;choice>
 *             &lt;element ref="{http://www.skupstinans.rs/akti}Clan"/>
 *             &lt;element ref="{http://www.skupstinans.rs/akti}Tacka"/>
 *             &lt;element ref="{http://www.skupstinans.rs/akti}Stav"/>
 *             &lt;element ref="{http://www.skupstinans.rs/akti}Alineja"/>
 *             &lt;element ref="{http://www.skupstinans.rs/akti}NormativniDeo"/>
 *           &lt;/choice>
 *           &lt;element name="Obrazlozenje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="korisnik" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="filename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="aktRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "naslov",
    "clanOrTackaOrStav"
})
@XmlRootElement(name = "Amandman")
public class Amandman {

    @XmlElement(name = "Naslov", required = true)
    protected String naslov;
    @XmlElements({
        @XmlElement(name = "Clan", namespace = "http://www.skupstinans.rs/akti", required = true, type = Clan.class),
        @XmlElement(name = "Tacka", namespace = "http://www.skupstinans.rs/akti", required = true, type = Tacka.class),
        @XmlElement(name = "Stav", namespace = "http://www.skupstinans.rs/akti", required = true, type = Stav.class),
        @XmlElement(name = "Alineja", namespace = "http://www.skupstinans.rs/akti", required = true, type = Alineja.class),
        @XmlElement(name = "NormativniDeo", namespace = "http://www.skupstinans.rs/akti", required = true, type = NormativniDeo.class),
        @XmlElement(name = "Obrazlozenje", required = true, type = String.class)
    })
    protected List<Object> clanOrTackaOrStav;
    @XmlAttribute(name = "korisnik")
    protected String korisnik;
    @XmlAttribute(name = "filename")
    protected String filename;
    @XmlAttribute(name = "aktRef")
    protected String aktRef;

    /**
     * Gets the value of the naslov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaslov() {
        return naslov;
    }

    /**
     * Sets the value of the naslov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaslov(String value) {
        this.naslov = value;
    }

    /**
     * Gets the value of the clanOrTackaOrStav property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clanOrTackaOrStav property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClanOrTackaOrStav().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Clan }
     * {@link Tacka }
     * {@link Stav }
     * {@link Alineja }
     * {@link NormativniDeo }
     * {@link String }
     * 
     * 
     */
    public List<Object> getClanOrTackaOrStav() {
        if (clanOrTackaOrStav == null) {
            clanOrTackaOrStav = new ArrayList<Object>();
        }
        return this.clanOrTackaOrStav;
    }

    /**
     * Gets the value of the korisnik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKorisnik() {
        return korisnik;
    }

    /**
     * Sets the value of the korisnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKorisnik(String value) {
        this.korisnik = value;
    }

    /**
     * Gets the value of the filename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilename() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilename(String value) {
        this.filename = value;
    }

    /**
     * Gets the value of the aktRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAktRef() {
        return aktRef;
    }

    /**
     * Sets the value of the aktRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAktRef(String value) {
        this.aktRef = value;
    }

}
