//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.13 at 01:26:08 AM CEST 
//


package entities.act;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.skupstinans.akti package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.skupstinans.akti
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Akt }
     * 
     */
    public Akt createAkt() {
        return new Akt();
    }

    /**
     * Create an instance of {@link Akt.NormativniDelovi }
     * 
     */
    public Akt.NormativniDelovi createAktNormativniDelovi() {
        return new Akt.NormativniDelovi();
    }

    /**
     * Create an instance of {@link Akt.NormativniDelovi.NormativniDeo }
     * 
     */
    public Akt.NormativniDelovi.NormativniDeo createAktNormativniDeloviNormativniDeo() {
        return new Akt.NormativniDelovi.NormativniDeo();
    }

    /**
     * Create an instance of {@link Akt.NormativniDelovi.NormativniDeo.Clan }
     * 
     */
    public Akt.NormativniDelovi.NormativniDeo.Clan createAktNormativniDeloviNormativniDeoClan() {
        return new Akt.NormativniDelovi.NormativniDeo.Clan();
    }

    /**
     * Create an instance of {@link Akt.NormativniDelovi.NormativniDeo.Clan.Stav }
     * 
     */
    public Akt.NormativniDelovi.NormativniDeo.Clan.Stav createAktNormativniDeloviNormativniDeoClanStav() {
        return new Akt.NormativniDelovi.NormativniDeo.Clan.Stav();
    }

    /**
     * Create an instance of {@link Akt.NormativniDelovi.NormativniDeo.Clan.Stav.Alineje }
     * 
     */
    public Akt.NormativniDelovi.NormativniDeo.Clan.Stav.Alineje createAktNormativniDeloviNormativniDeoClanStavAlineje() {
        return new Akt.NormativniDelovi.NormativniDeo.Clan.Stav.Alineje();
    }

    /**
     * Create an instance of {@link Akt.NormativniDelovi.NormativniDeo.Clan.Stav.Alineje.Alineja }
     * 
     */
    public Akt.NormativniDelovi.NormativniDeo.Clan.Stav.Alineje.Alineja createAktNormativniDeloviNormativniDeoClanStavAlinejeAlineja() {
        return new Akt.NormativniDelovi.NormativniDeo.Clan.Stav.Alineje.Alineja();
    }

    /**
     * Create an instance of {@link Akt.NormativniDelovi.NormativniDeo.Clan.Stav.Alineje.Alineja.Podalineje }
     * 
     */
    public Akt.NormativniDelovi.NormativniDeo.Clan.Stav.Alineje.Alineja.Podalineje createAktNormativniDeloviNormativniDeoClanStavAlinejeAlinejaPodalineje() {
        return new Akt.NormativniDelovi.NormativniDeo.Clan.Stav.Alineje.Alineja.Podalineje();
    }

    /**
     * Create an instance of {@link Akt.Tacke }
     * 
     */
    public Akt.Tacke createAktTacke() {
        return new Akt.Tacke();
    }

    /**
     * Create an instance of {@link Akt.Tacke.Tacka }
     * 
     */
    public Akt.Tacke.Tacka createAktTackeTacka() {
        return new Akt.Tacke.Tacka();
    }

    /**
     * Create an instance of {@link Akt.Tacke.Tacka.Podtacka }
     * 
     */
    public Akt.Tacke.Tacka.Podtacka createAktTackeTackaPodtacka() {
        return new Akt.Tacke.Tacka.Podtacka();
    }

    /**
     * Create an instance of {@link Akt.Tacke.Tacka.Podtacka.Stavpodtacke }
     * 
     */
    public Akt.Tacke.Tacka.Podtacka.Stavpodtacke createAktTackeTackaPodtackaStavpodtacke() {
        return new Akt.Tacke.Tacka.Podtacka.Stavpodtacke();
    }

    /**
     * Create an instance of {@link Akt.Tacke.Tacka.Podtacka.Stavpodtacke.Alineje }
     * 
     */
    public Akt.Tacke.Tacka.Podtacka.Stavpodtacke.Alineje createAktTackeTackaPodtackaStavpodtackeAlineje() {
        return new Akt.Tacke.Tacka.Podtacka.Stavpodtacke.Alineje();
    }

    /**
     * Create an instance of {@link Akt.Tacke.Tacka.Podtacka.Stavpodtacke.Alineje.Alineja }
     * 
     */
    public Akt.Tacke.Tacka.Podtacka.Stavpodtacke.Alineje.Alineja createAktTackeTackaPodtackaStavpodtackeAlinejeAlineja() {
        return new Akt.Tacke.Tacka.Podtacka.Stavpodtacke.Alineje.Alineja();
    }

    /**
     * Create an instance of {@link Akt.Tacke.Tacka.Podtacka.Stavpodtacke.Alineje.Alineja.Podalineje }
     * 
     */
    public Akt.Tacke.Tacka.Podtacka.Stavpodtacke.Alineje.Alineja.Podalineje createAktTackeTackaPodtackaStavpodtackeAlinejeAlinejaPodalineje() {
        return new Akt.Tacke.Tacka.Podtacka.Stavpodtacke.Alineje.Alineja.Podalineje();
    }

    /**
     * Create an instance of {@link Akt.Tacke.Tacka.Stav }
     * 
     */
    public Akt.Tacke.Tacka.Stav createAktTackeTackaStav() {
        return new Akt.Tacke.Tacka.Stav();
    }

    /**
     * Create an instance of {@link Akt.Tacke.Tacka.Stav.Alineje }
     * 
     */
    public Akt.Tacke.Tacka.Stav.Alineje createAktTackeTackaStavAlineje() {
        return new Akt.Tacke.Tacka.Stav.Alineje();
    }

    /**
     * Create an instance of {@link Akt.Tacke.Tacka.Stav.Alineje.Alineja }
     * 
     */
    public Akt.Tacke.Tacka.Stav.Alineje.Alineja createAktTackeTackaStavAlinejeAlineja() {
        return new Akt.Tacke.Tacka.Stav.Alineje.Alineja();
    }

    /**
     * Create an instance of {@link Akt.Tacke.Tacka.Stav.Alineje.Alineja.Podalineje }
     * 
     */
    public Akt.Tacke.Tacka.Stav.Alineje.Alineja.Podalineje createAktTackeTackaStavAlinejeAlinejaPodalineje() {
        return new Akt.Tacke.Tacka.Stav.Alineje.Alineja.Podalineje();
    }

    /**
     * Create an instance of {@link Akt.NormativniDelovi.NormativniDeo.Clan.Stav.Alineje.Alineja.Podalineje.Alinejapodalineje }
     * 
     */
    public Akt.NormativniDelovi.NormativniDeo.Clan.Stav.Alineje.Alineja.Podalineje.Alinejapodalineje createAktNormativniDeloviNormativniDeoClanStavAlinejeAlinejaPodalinejeAlinejapodalineje() {
        return new Akt.NormativniDelovi.NormativniDeo.Clan.Stav.Alineje.Alineja.Podalineje.Alinejapodalineje();
    }

    /**
     * Create an instance of {@link Akt.Tacke.Tacka.Podtacka.Stavpodtacke.Alineje.Alineja.Podalineje.Alinejapodalineje }
     * 
     */
    public Akt.Tacke.Tacka.Podtacka.Stavpodtacke.Alineje.Alineja.Podalineje.Alinejapodalineje createAktTackeTackaPodtackaStavpodtackeAlinejeAlinejaPodalinejeAlinejapodalineje() {
        return new Akt.Tacke.Tacka.Podtacka.Stavpodtacke.Alineje.Alineja.Podalineje.Alinejapodalineje();
    }

    /**
     * Create an instance of {@link Akt.Tacke.Tacka.Stav.Alineje.Alineja.Podalineje.Alinejapodalineje }
     * 
     */
    public Akt.Tacke.Tacka.Stav.Alineje.Alineja.Podalineje.Alinejapodalineje createAktTackeTackaStavAlinejeAlinejaPodalinejeAlinejapodalineje() {
        return new Akt.Tacke.Tacka.Stav.Alineje.Alineja.Podalineje.Alinejapodalineje();
    }

}
