//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 03:50:04 PM CEST 
//


package entities.act;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.skupstinans.akti package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.skupstinans.akti
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Stav }
     * 
     */
    public Stav createStav() {
        return new Stav();
    }

    /**
     * Create an instance of {@link Tacka }
     * 
     */
    public Tacka createTacka() {
        return new Tacka();
    }

    /**
     * Create an instance of {@link Alineja }
     * 
     */
    public Alineja createAlineja() {
        return new Alineja();
    }

    /**
     * Create an instance of {@link Akt }
     * 
     */
    public Akt createAkt() {
        return new Akt();
    }

    /**
     * Create an instance of {@link Alineja.Podalineje }
     * 
     */
    public Alineja.Podalineje createAlinejaPodalineje() {
        return new Alineja.Podalineje();
    }

    /**
     * Create an instance of {@link Stav.Alineje }
     * 
     */
    public Stav.Alineje createStavAlineje() {
        return new Stav.Alineje();
    }

    /**
     * Create an instance of {@link Tacka.Podtacka }
     * 
     */
    public Tacka.Podtacka createTackaPodtacka() {
        return new Tacka.Podtacka();
    }

    /**
     * Create an instance of {@link Clan }
     * 
     */
    public Clan createClan() {
        return new Clan();
    }

    /**
     * Create an instance of {@link NormativniDeo }
     * 
     */
    public NormativniDeo createNormativniDeo() {
        return new NormativniDeo();
    }

    /**
     * Create an instance of {@link Akt.Tacke }
     * 
     */
    public Akt.Tacke createAktTacke() {
        return new Akt.Tacke();
    }

    /**
     * Create an instance of {@link Akt.NormativniDelovi }
     * 
     */
    public Akt.NormativniDelovi createAktNormativniDelovi() {
        return new Akt.NormativniDelovi();
    }

    /**
     * Create an instance of {@link Alineja.Podalineje.Alinejapodalineje }
     * 
     */
    public Alineja.Podalineje.Alinejapodalineje createAlinejaPodalinejeAlinejapodalineje() {
        return new Alineja.Podalineje.Alinejapodalineje();
    }

}
