//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 03:50:04 PM CEST 
//


package entities.act;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.skupstinans.rs/akti}Stav" maxOccurs="unbounded"/>
 *         &lt;element name="Podtacka" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.skupstinans.rs/akti}Stav"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="BrojPodtacke" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="BrojTacke" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stav",
    "podtacka"
})
@XmlRootElement(name = "Tacka")
public class Tacka {

    @XmlElement(name = "Stav", required = true)
    protected List<Stav> stav;
    @XmlElement(name = "Podtacka")
    protected List<Tacka.Podtacka> podtacka;
    @XmlAttribute(name = "BrojTacke", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger brojTacke;

    /**
     * Gets the value of the stav property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stav property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStav().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Stav }
     * 
     * 
     */
    public List<Stav> getStav() {
        if (stav == null) {
            stav = new ArrayList<Stav>();
        }
        return this.stav;
    }

    /**
     * Gets the value of the podtacka property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the podtacka property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPodtacka().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tacka.Podtacka }
     * 
     * 
     */
    public List<Tacka.Podtacka> getPodtacka() {
        if (podtacka == null) {
            podtacka = new ArrayList<Tacka.Podtacka>();
        }
        return this.podtacka;
    }

    /**
     * Gets the value of the brojTacke property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrojTacke() {
        return brojTacke;
    }

    /**
     * Sets the value of the brojTacke property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrojTacke(BigInteger value) {
        this.brojTacke = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.skupstinans.rs/akti}Stav"/>
     *       &lt;/sequence>
     *       &lt;attribute name="BrojPodtacke" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stav"
    })
    public static class Podtacka {

        @XmlElement(name = "Stav", required = true)
        protected Stav stav;
        @XmlAttribute(name = "BrojPodtacke")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger brojPodtacke;

        /**
         * Gets the value of the stav property.
         * 
         * @return
         *     possible object is
         *     {@link Stav }
         *     
         */
        public Stav getStav() {
            return stav;
        }

        /**
         * Sets the value of the stav property.
         * 
         * @param value
         *     allowed object is
         *     {@link Stav }
         *     
         */
        public void setStav(Stav value) {
            this.stav = value;
        }

        /**
         * Gets the value of the brojPodtacke property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBrojPodtacke() {
            return brojPodtacke;
        }

        /**
         * Sets the value of the brojPodtacke property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBrojPodtacke(BigInteger value) {
            this.brojPodtacke = value;
        }

    }

}
